[versions]

androidx-camera = "1.3.1"
androidx-cameraView = "1.1.0"
androidx-paging = "3.2.1"
androidx-room = "2.6.1"
androidx-work = "2.9.0"
androidx-security-crypto = "1.1.0-alpha06"
androidx-viewmodel = "2.7.0"
androidx-lifecycle = "2.6.2"

dagger = "2.51.1"

flipper = "0.176.0"

kotlin = "1.9.10"

ktlint = "0.36.0"

lint = "31.0.2"

mobius = "1.5.14"

moshi = "1.14.0"

okhttp = "4.10.0"

retrofit = "2.9.0"

room-metadataGenerator = "2.0.1"

rx-binding = "3.1.0"

coroutines = "1.8.0"

compose-compiler = "1.5.3"

androidx-compose-bom = "2023.07.00-alpha02"

composeThemeAdapter = "0.34.0"

ksp = "1.9.10-1.0.13"

sqlCipher = "4.5.4"

[libraries]
android-gradle-plugin = "com.android.tools.build:gradle:8.3.1"
android-desugaring = "com.android.tools:desugar_jdk_libs:2.0.4"

androidx-annotation-annotation = "androidx.annotation:annotation:1.7.1"

# When bumping this dependency verify whether `org.simple.clinic.feature.Feature.ChangeLanguage`
# can be enabled again.
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"

androidx-archCoreTesting = "androidx.arch.core:core-testing:2.1.0"
androidx-cardview = "androidx.cardview:cardview:1.0.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core-ktx = "androidx.core:core-ktx:1.9.0"
androidx-fragment = "androidx.fragment:fragment-ktx:1.5.7"
androidx-preference = "androidx.preference:preference:1.2.1"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.2.1"
androidx-viewpager2 = "androidx.viewpager2:viewpager2:1.0.0"

androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "androidx-camera" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "androidx-camera" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "androidx-cameraView" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "androidx-camera" }

androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
androidx-paging-rx2 = { module = "androidx.paging:paging-rxjava2", version.ref = "androidx-paging" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-rx2 = { module = "androidx.room:room-rxjava2", version.ref = "androidx-room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }

androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-junit = "androidx.test.ext:junit:1.1.5"
androidx-test-rules = "androidx.test:rules:1.5.0"

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidx-work-rxjava = { module = "androidx.work:work-rxjava2", version.ref = "androidx-work" }
androidx-work-gcm = { module = "androidx.work:work-gcm", version.ref = "androidx-work" }

androidx-security-crypto = { module = "androidx.security:security-crypto-ktx", version.ref = "androidx-security-crypto" }

androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-viewmodel" }
androidx-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-viewmodel" }

androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }

asm = "org.ow2.asm:asm:9.4"

dagger-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

edittext-masked = "com.github.egslava:edittext-mask:1.0.7"
edittext-pinentry = "com.alimuzaffar.lib:pinentryedittext:2.0.6"

faker = "com.github.blocoio:faker:1.2.9"

firebase-config = "com.google.firebase:firebase-config:21.2.0"
firebase-analytics = "com.google.firebase:firebase-analytics-ktx:21.3.0"

flipper-flipper = { module = "com.facebook.flipper:flipper", version.ref = "flipper" }
flipper-networkPlugin = { module = "com.facebook.flipper:flipper-network-plugin", version.ref = "flipper" }

gson = "com.google.code.gson:gson:2.10.1"

google-services = "com.google.gms:google-services:4.3.15"

itemanimators = "com.mikepenz:itemanimators:1.1.0"

itext7 = "com.itextpdf:itext7-core:7.2.5"

jackson-core = "com.fasterxml.jackson.core:jackson-core:2.14.2"

jbcrypt = "org.mindrot:jbcrypt:0.4"

junit = "junit:junit:4.13.2"
junitParams = "pl.pragmatists:JUnitParams:1.1.1"

kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

leakcanary = "com.squareup.leakcanary:leakcanary-android:2.10"

lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lint-checks = { module = "com.android.tools.lint:lint-checks", version.ref = "lint" }
lint-lint = { module = "com.android.tools.lint:lint", version.ref = "lint" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }

logback-classic = "ch.qos.logback:logback-classic:1.2.11"

lottie = "com.airbnb.android:lottie:5.2.0"

material = "com.google.android.material:material:1.9.0"

mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:4.1.0"

mobius-android = { module = "com.spotify.mobius:mobius-android", version.ref = "mobius" }
mobius-core = { module = "com.spotify.mobius:mobius-core", version.ref = "mobius" }
mobius-extras = { module = "com.spotify.mobius:mobius-extras", version.ref = "mobius" }
mobius-rx2 = { module = "com.spotify.mobius:mobius-rx2", version.ref = "mobius" }
mobius-test = { module = "com.spotify.mobius:mobius-test", version.ref = "mobius" }

moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
moshi-moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }

okhttp-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-interceptor-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

openCsv = "com.opencsv:opencsv:5.7.1"

play-core = "com.google.android.play:core:1.10.3"
play-services-auth = "com.google.android.gms:play-services-auth:20.4.1"
play-services-location = "com.google.android.gms:play-services-location:21.0.1"
play-services-mlkit-barcode = "com.google.android.gms:play-services-mlkit-barcode-scanning:18.1.0"

rootbeer = "com.scottyab:rootbeer-lib:0.1.0"

retrofit-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-rx = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }

rx-android = "io.reactivex.rxjava2:rxandroid:2.1.1"
rx-binding-appcompat = { module = "com.jakewharton.rxbinding3:rxbinding-appcompat", version.ref = "rx-binding" }
rx-binding-binding = { module = "com.jakewharton.rxbinding3:rxbinding", version.ref = "rx-binding" }
rx-binding-recyclerview = { module = "com.jakewharton.rxbinding3:rxbinding-recyclerview", version.ref = "rx-binding" }
rx-java = "io.reactivex.rxjava2:rxjava:2.2.21"
rx-kotlin = "io.reactivex.rxjava2:rxkotlin:2.4.0"
rx-preferences = "com.f2prateek.rx.preferences2:rx-preferences:2.0.1"

sentry-android = "io.sentry:sentry-android:6.22.0"
sentry-gradle-plugin = "io.sentry:sentry-android-gradle-plugin:3.10.0"

signaturepad = "com.github.gcacace:signature-pad:1.3.1"

soloader = "com.facebook.soloader:soloader:0.10.5"

sqlite-android = "com.github.requery:sqlite-android:3.39.2"

threeten-extra = "org.threeten:threeten-extra:1.7.2"

timber = "com.jakewharton.timber:timber:5.0.1"

traceur = "com.github.qoqa:Traceur:2.2.12"

truth = "com.google.truth:truth:1.1.5"

uuid-generator = "com.fasterxml.uuid:java-uuid-generator:4.0.1"

viewpump = "io.github.inflationx:viewpump:2.0.3"

datadog-sdk = "com.datadoghq:dd-sdk-android:1.15.0"
datadog-gradle-plugin = "com.datadoghq:dd-sdk-android-gradle-plugin:1.5.1"

zxing = "com.google.zxing:core:3.3.3"

apache-commons-math = "org.apache.commons:commons-math3:3.6.1"

benchmark-gradle-plugin = "androidx.benchmark:benchmark-gradle-plugin:1.1.1"

androidx-compose-bom = { module = "dev.chrisbanes.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material-iconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-materialWindow = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
composeThemeAdapter = { module = "com.google.accompanist:accompanist-themeadapter-material", version.ref = "composeThemeAdapter" }
composeThemeAdapterCore = { module = "com.google.accompanist:accompanist-themeadapter-core", version.ref = "composeThemeAdapter" }
androidx-compose-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-compose-test-junit = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

sqlCipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "sqlCipher" }

[bundles]
androidx-camera = ["androidx-camera-core", "androidx-camera-camera2", "androidx-camera-view", "androidx-camera-lifecycle"]
androidx-paging = ["androidx-paging-common", "androidx-paging-runtime", "androidx-paging-rx2"]
androidx-room = ["androidx-room-runtime", "androidx-room-rx2", "androidx-room-paging"]
androidx-test = ["androidx-test-junit", "androidx-test-runner", "androidx-test-rules"]
androidx-work = ["androidx-work-runtime", "androidx-work-rxjava", "androidx-work-gcm"]

flipper = ["flipper-flipper", "flipper-networkPlugin"]

lint = ["lint-api", "lint-checks"]

mobius = ["mobius-android", "mobius-core", "mobius-extras", "mobius-rx2"]

moshi = ["moshi-moshi", "moshi-adapters"]

okhttp = ["okhttp-okhttp", "okhttp-interceptor-logging"]

retrofit = ["retrofit-retrofit", "retrofit-rx", "retrofit-moshi", "retrofit-scalars"]

rx-binding = ["rx-binding-appcompat", "rx-binding-binding", "rx-binding-recyclerview"]
