[versions]

androidx-camera = "1.0.2"
androidx-cameraView = "1.0.0-alpha29"
androidx-paging = "3.0.1"
androidx-room = "2.3.0"
androidx-test = "1.4.0"
androidx-work = "2.7.0"

dagger = "2.40"

dependencyUpdates = "0.38.0"

flipper = "0.98.0"

kotlin = "1.5.31"

ktlint = "0.36.0"

lint = "30.0.1"

mobius = "1.5.6"

moshi = "1.12.0"

okhttp = "4.9.1"

retrofit = "2.9.0"

room-metadataGenerator = "2.0.0"

rx-binding = "3.1.0"

spotless = "5.6.1"

[plugins]
dependencyUpdates = { id = "com.github.ben-manes.versions", version.ref = "dependencyUpdates" }

spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
android-gradle-plugin = "com.android.tools.build:gradle:7.0.3"
android-desugaring = "com.android.tools:desugar_jdk_libs:1.0.9"

androidx-annotation-annotation = "androidx.annotation:annotation:1.2.0"
androidx-annotation-experimental = "androidx.annotation:annotation-experimental:1.1.0"

# When bumping this dependency verify whether `org.simple.clinic.feature.Feature.ChangeLanguage`
# can be enabled again.
androidx-appcompat = "androidx.appcompat:appcompat:1.3.1"

androidx-archCoreTesting = "androidx.arch.core:core-testing:2.1.0"
androidx-cardview = "androidx.cardview:cardview:1.0.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.0.4"
androidx-core-ktx = "androidx.core:core-ktx:1.7.0"
androidx-fragment = "androidx.fragment:fragment-ktx:1.3.6"
androidx-preference = "androidx.preference:preference:1.1.1"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.2.1"
androidx-viewpager2 = "androidx.viewpager2:viewpager2:1.0.0"

androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "androidx-camera" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "androidx-camera" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "androidx-cameraView" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "androidx-camera" }

androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
androidx-paging-rx2 = { module = "androidx.paging:paging-rxjava2", version.ref = "androidx-paging" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-rx2 = { module = "androidx.room:room-rxjava2", version.ref = "androidx-room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }

androidx-test-junit = "androidx.test.ext:junit:1.1.3"
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidx-work-gcm = { module = "androidx.work:work-gcm", version.ref = "androidx-work" }

asm = "org.ow2.asm:asm:9.2"

dagger-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

edittext-masked = "com.github.egslava:edittext-mask:1.0.7"
edittext-pinentry = "com.alimuzaffar.lib:pinentryedittext:2.0.6"

faker = "com.github.blocoio:faker:1.2.8"

firebase-config = "com.google.firebase:firebase-config:21.0.0"

flipper-flipper = { module = "com.facebook.flipper:flipper", version.ref = "flipper" }
flipper-networkPlugin = { module = "com.facebook.flipper:flipper-network-plugin", version.ref = "flipper" }

google-services = "com.google.gms:google-services:4.3.3"

guava = "com.google.guava:guava:28.1-jre"

itemanimators = "com.mikepenz:itemanimators:1.0.2"

itext7 = "com.itextpdf:itext7-core:7.1.16"

jackson-core = "com.fasterxml.jackson.core:jackson-core:2.12.4"

jbcrypt = "org.mindrot:jbcrypt:0.4"

junit = "junit:junit:4.13.2"
junitParams = "pl.pragmatists:JUnitParams:1.1.1"

kotlin-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2:1.5.2"
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

leakcanary = "com.squareup.leakcanary:leakcanary-android:2.7"

lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lint-checks = { module = "com.android.tools.lint:lint-checks", version.ref = "lint" }
lint-lint = { module = "com.android.tools.lint:lint", version.ref = "lint" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }

logback-classic = "ch.qos.logback:logback-classic:1.2.5"

lottie = "com.airbnb.android:lottie:4.1.0"

material = "com.google.android.material:material:1.4.0"

mixpanel-android = "com.mixpanel.android:mixpanel-android:5.9.5"

mockito-kotlin = "com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0"

mobius-android = { module = "com.spotify.mobius:mobius-android", version.ref = "mobius" }
mobius-core = { module = "com.spotify.mobius:mobius-core", version.ref = "mobius" }
mobius-extras = { module = "com.spotify.mobius:mobius-extras", version.ref = "mobius" }
mobius-rx2 = { module = "com.spotify.mobius:mobius-rx2", version.ref = "mobius" }
mobius-test = { module = "com.spotify.mobius:mobius-test", version.ref = "mobius" }

moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
moshi-moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }

okhttp-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-interceptor-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

openCsv = "com.opencsv:opencsv:5.5.2"

play-core = "com.google.android.play:core:1.10.0"
play-services-auth = "com.google.android.gms:play-services-auth:19.0.0"
play-services-location = "com.google.android.gms:play-services-location:18.0.0"
play-services-mlkit-barcode = "com.google.android.gms:play-services-mlkit-barcode-scanning:16.2.0"

rootbeer = "com.scottyab:rootbeer-lib:0.0.9"

retrofit-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-rx = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }

rx-android = "io.reactivex.rxjava2:rxandroid:2.1.1"
rx-binding-appcompat = { module = "com.jakewharton.rxbinding3:rxbinding-appcompat", version.ref = "rx-binding" }
rx-binding-binding = { module = "com.jakewharton.rxbinding3:rxbinding", version.ref = "rx-binding" }
rx-binding-recyclerview = { module = "com.jakewharton.rxbinding3:rxbinding-recyclerview", version.ref = "rx-binding" }
rx-java = "io.reactivex.rxjava2:rxjava:2.2.21"
rx-kotlin = "io.reactivex.rxjava2:rxkotlin:2.4.0"
rx-preferences = "com.f2prateek.rx.preferences2:rx-preferences:2.0.1"

sentry-android = "io.sentry:sentry-android:4.3.0"
sentry-gradle-plugin = "io.sentry:sentry-android-gradle-plugin:2.0.1"

signaturepad = "com.github.gcacace:signature-pad:1.3.1"

soloader = "com.facebook.soloader:soloader:0.10.1"

sqlite-android = "com.github.requery:sqlite-android:3.36.0"

threeten-extra = "org.threeten:threeten-extra:1.7.0"

timber = "com.jakewharton.timber:timber:5.0.1"

traceur = "com.github.qoqa:Traceur:2.2.12"

truth = "com.google.truth:truth:1.1.2"

uuid-generator = "com.fasterxml.uuid:java-uuid-generator:4.0.1"

viewpump = "io.github.inflationx:viewpump:2.0.3"

datadog-sdk = "com.datadoghq:dd-sdk-android:1.10.0"
datadog-gradle-plugin = "com.datadoghq:dd-sdk-android-gradle-plugin:1.1.0"

zxing = { group = "com.google.zxing", name = "core", version = { strictly = "[3.3, 3.4[", prefer = "3.3.3" } }

[bundles]
androidx-camera = ["androidx-camera-core", "androidx-camera-camera2", "androidx-camera-view", "androidx-camera-lifecycle"]
androidx-paging = ["androidx-paging-common", "androidx-paging-runtime", "androidx-paging-rx2"]
androidx-room = ["androidx-room-runtime", "androidx-room-rx2"]
androidx-test = ["androidx-test-junit", "androidx-test-runner", "androidx-test-rules"]
androidx-work = ["androidx-work-runtime", "androidx-work-gcm"]

flipper = ["flipper-flipper", "flipper-networkPlugin"]

lint = ["lint-api", "lint-checks"]

mobius = ["mobius-android", "mobius-core", "mobius-extras", "mobius-rx2"]

moshi = ["moshi-moshi", "moshi-adapters"]

okhttp = ["okhttp-okhttp", "okhttp-interceptor-logging"]

retrofit = ["retrofit-retrofit", "retrofit-rx", "retrofit-moshi", "retrofit-scalars"]

rx-binding = ["rx-binding-appcompat", "rx-binding-binding", "rx-binding-recyclerview"]
