filters:
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: Android
    source_language: en
    source_file: app/src/main/res/values/strings.xml
   # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: 'app/src/main/res/values-<lang>/strings.xml'
settings:
  language_mapping:
    am_ET: am-rET
    bn_BD: bn-rBD
    bn_IN: bn-rIN
    hi_IN: hi-rIN
    kn_IN: kn-rIN
    mr: mr-rIN
    om: om-rET
    pa: pa-rIN
    si_LK: si-rLK
    sid: id-rET
    so: so-rET
    ta_IN: ta-rIN
    ta_LK: ta-rLK
    te_IN: te-rIN
    ti: ti-rET
