name: Code formatting

# Scheduled at 11:30 PM UTC (Sunday to Thursday)
# Scheduled at 05:00 AM IST (Monday to Friday)
on:
#  schedule:
#    - cron: "30 23 * * 0-4"
  workflow_dispatch:

jobs:
  fix_code_formatting:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Fix code formatting issues
        run: ./gradlew spotlessApply

      - name: Commit and Push
        id: commit_and_push
        run: .github/scripts/commit_and_push.sh "${{secrets.USER_NAME}}" "${{secrets.USER_EMAIL}}"

      - name: Create PR
        uses: actions/github-script@0.3.0
        env:
          branch_name: ${{steps.commit_and_push.outputs.branch_name}}
        with:
          github-token: ${{secrets.GITHUB_ACCESS_TOKEN}}
          script: |
            const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
            const branchName = process.env.branch_name
            const date = new Date();
            const month = monthNames[date.getMonth()];
            const day = `${date.getDate()}`.padStart(2, '0');
            const year = `${date.getFullYear()}`
            const prTitle = `[BOT] Code formatting fixes ${month}-${day}-${year}`

            if (branchName) {
                const branch = await github.repos.getBranch({
                    ...context.repo,
                    branch: branchName
                });
                await github.pulls.create({
                    ...context.repo,
                    title: prTitle,
                    head: branch.data.name,
                    base: 'master'
                });
            }
